version: "3"

services:

  exp:
    container_name: 'dockerized-exp'
    build:
      context: ./services/exp
    tty: true
    stdin_open: true
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"

  alpine:
    container_name: 'dockerized-alpine'
    image: alpine:latest

  debian:
    container_name: 'dockerized-debian'
    image: debian:stretch-slim

  apache:
    container_name: 'dockerized-apache'
    build:
      context: ./services/apache
      args:
        - DEFAULT_PHP_VER=${DEFAULT_PHP_VER-7.3}
        - FPM_INSTALL_PHP_53=${INSTALL_PHP_53-false}
        - FPM_INSTALL_PHP_54=${INSTALL_PHP_54-false}
        - FPM_INSTALL_PHP_55=${INSTALL_PHP_55-false}
        - FPM_INSTALL_PHP_56=${INSTALL_PHP_56-false}
        - FPM_INSTALL_PHP_70=${INSTALL_PHP_70-false}
        - FPM_INSTALL_PHP_71=${INSTALL_PHP_71-false}
        - FPM_INSTALL_PHP_72=${INSTALL_PHP_72-false}
        - FPM_INSTALL_PHP_73=${INSTALL_PHP_73-true}
    ports:
      - "${APACHE_PORT-80}:80"
      - "${APACHE_PORT_SSL-443}:443"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    volumes:
      - ./services/apache/apache2/vhosts/vhosts.conf:/etc/apache2/sites-enabled/vhosts.conf
      - ${DOCUMENT_ROOT-./volumes/var/www/html}:/var/www/html
      - ${APACHE_LOG_DIR-./volumes/var/log/apache2}:/var/log/apache2

  nginx:
    container_name: 'dockerized-nginx'
    build:
      context: ./services/nginx
      args:
        - NGINX_PHP_VER=${NGINX_PHP_VER-7.3}
    ports:
      - "${NGINX_PORT-80}:80"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    volumes:
      - ${DOCUMENT_ROOT-./volumes/var/www/html}:/var/www/html
      - ${NGINX_LOG_DIR-./volumes/var/log/nginx}:/var/log/nginx

  mysql:
    container_name: 'dockerized-mysql'
    image: mysql:latest
    ports:
      - "${MYSQL_PORT-3306}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./volumes/var/lib/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./volumes/var/log/mysql}:/var/log/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER-dockerized}
      MYSQL_PASSWORD: ${MYSQL_USER_PASS-dockerized}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS-root}
      MYSQL_DATABASE: ${MYSQL_DB-dockerized}

  mariadb:
    container_name: 'dockerized-mariadb'
    image: mariadb:latest
    ports:
      - "${MARIADB_PORT-3306}:3306"
    volumes:
      - ${MARIADB_DATA_DIR-./volumes/var/lib/mariadb}:/var/lib/mysql
      - ${MARIADB_LOG_DIR-./volumes/var/log/mariadb}:/var/log/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER-dockerized}
      MYSQL_PASSWORD: ${MYSQL_USER_PASS-dockerized}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS-root}
      MYSQL_DATABASE: ${MYSQL_DB-dockerized}

  mongo:
    container_name: 'dockerized-mongodb'
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS-root}

  postgres:
    container_name: 'dockerized-postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASS-root}

  redis:
    container_name: 'dockerized-redis'
    image: redis:alpine
    ports:
      - "${REDIS_PORT-6379}:6379"

  memcached:
    container_name: 'dockerized-memcached'
    image: memcached:alpine
    ports:
      - "${MEMCACHED_PORT-11211}:11211"

  void:
    container_name: 'dockerized-void'
    build:
      context: ./services/void
      args:
        - VOID_USER=${VOID_USER-copernicus}
        - VOID_USE_BD_MIRROR=${VOID_USE_BD_MIRROR-false}
        - VOID_ADD_NODEJS=${VOID_ADD_NODEJS-true}
        - VOID_ADD_RUBY=${VOID_ADD_RUBY-false}
        - VOID_ADD_JDK=${VOID_ADD_JDK-false}
        - VOID_ADD_PYTHON=${VOID_ADD_PYTHON-false}
        - VOID_ADD_COMPOSER=${VOID_ADD_COMPOSER-true}
        - VOID_ADD_DRUSH=${VOID_ADD_DRUSH-true}
        - VOID_ADD_DRUPALCONSOLE=${VOID_ADD_DRUPALCONSOLE-true}
        - VOID_ADD_WPCLI=${VOID_ADD_WPCLI-true}
    tty: true
    stdin_open: true
    ports:
      - "${VOID_SSH_PORT-2222}:22"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - DOCUMENT_ROOT=${DOCUMENT_ROOT-/var/www/html}
    volumes:
      - ${DOCUMENT_ROOT-./volumes/var/www/html}:/var/www/html
      - ./volumes/data/share:/data/share
      - ./volumes/root/.ssh:/root/.ssh
      - ./volumes/home/${VOID_USER-copernicus}/.ssh:/home/${VOID_USER-copernicus}/.ssh
