version: "3"

networks:
  skynet:

services:
  fpm:
    container_name: 'dockerized-fpm'
    build:
      context: ./services/fpm
      args:
        - USE_BD_MIRRORS=${USE_BD_MIRRORS-false}
        - ADD_PHP_56=${ADD_PHP_56-false}
        - ADD_PHP_74=${ADD_PHP_74-true}
        - ADD_PHP_73=${ADD_PHP_73-true}
        - ADD_PHP_72=${ADD_PHP_72-false}
        - ADD_PHP_71=${ADD_PHP_71-false}
        - ADD_PHP_70=${ADD_PHP_70-false}
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    restart: ${RESTART_FPM-no}
    tty: true
    volumes:
      - ${DOCUMENT_ROOT-./volumes/var/www/html}:/var/www/html
      - ${CACHE_DIR-./volumes/var/cachedir}:/var/cachedir
      - ./services/fpm/config/php/ini/php5.6.ini:/etc/php/5.6/fpm/php.ini
      - ./services/fpm/config/php/ini/php7.4.ini:/etc/php/7.4/fpm/php.ini
      - ./services/fpm/config/php/ini/php7.3.ini:/etc/php/7.3/fpm/php.ini
      - ./services/fpm/config/php/ini/php7.2.ini:/etc/php/7.2/fpm/php.ini
      - ./services/fpm/config/php/ini/php7.1.ini:/etc/php/7.1/fpm/php.ini
      - ./services/fpm/config/php/ini/php7.0.ini:/etc/php/7.0/fpm/php.ini
    networks:
      - skynet

  apache:
    container_name: 'dockerized-apache'
    build:
      context: ./services/apache
      args:
        - APACHE_PHP_VER=${APACHE_PHP_VER-7.4}
    ports:
      - "${APACHE_PORT-80}:80"
      - "${APACHE_PORT_SSL-443}:443"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    restart: ${RESTART_APACHE-no}
    tty: true
    volumes:
      - ./services/apache/conf/dockerized.conf:/etc/apache2/conf-enabled/dockerized.conf
      - ./services/apache/conf/vhosts.conf:/etc/apache2/sites-enabled/vhosts.conf
      - ${DOCUMENT_ROOT-./volumes/var/www/html}:/var/www/html
      - ${CACHE_DIR-./volumes/var/cachedir}:/var/cachedir
      - ${APACHE_LOG_DIR-./volumes/var/log/apache2}:/var/log/apache2
    networks:
      - skynet
    depends_on:
      - fpm

  nginx:
    container_name: 'dockerized-nginx'
    build:
      context: ./services/nginx
      args:
        - NGINX_PHP_VER=${NGINX_PHP_VER-7.4}
    ports:
      - "${NGINX_PORT-80}:80"
      - "${NGINX_PORT_SSL-443}:443"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    restart: ${RESTART_NGINX-no}
    volumes:
      - ./services/nginx/conf/dockerized.conf:/etc/nginx/conf.d/dockerized.conf
      - ./services/nginx/conf/vhosts.conf:/etc/nginx/sites-enabled/vhosts.conf
      - ${DOCUMENT_ROOT-./volumes/var/www/html}:/var/www/html
      - ${CACHE_DIR-./volumes/var/cachedir}:/var/cachedir
      - ${NGINX_LOG_DIR-./volumes/var/log/nginx}:/var/log/nginx
    networks:
      - skynet
    depends_on:
      - fpm

  mysql:
    container_name: 'dockerized-mysql'
    image: mysql:latest
    restart: ${RESTART_MYSQL-no}
    ports:
      - "${MYSQL_PORT-3306}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./volumes/var/lib/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./volumes/var/log/mysql}:/var/log/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER-dockerized}
      MYSQL_PASSWORD: ${MYSQL_USER_PASS-dockerized}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS-root}
      MYSQL_DATABASE: ${MYSQL_DB-dockerized}
    networks:
      - skynet

  mariadb:
    container_name: 'dockerized-mariadb'
    image: mariadb:latest
    restart: ${RESTART_MARIADB-no}
    ports:
      - "${MARIADB_PORT-3306}:3306"
    volumes:
      - ${MARIADB_DATA_DIR-./volumes/var/lib/mariadb}:/var/lib/mysql
      - ${MARIADB_LOG_DIR-./volumes/var/log/mariadb}:/var/log/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER-dockerized}
      MYSQL_PASSWORD: ${MYSQL_USER_PASS-dockerized}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS-root}
      MYSQL_DATABASE: ${MYSQL_DB-dockerized}
    networks:
      - skynet

  mongo:
    container_name: 'dockerized-mongodb'
    image: mongo
    restart: ${RESTART_MONGO-no}
    volumes:
      - ${MONGO_DATA_DIR-./volumes/data/db}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS-root}
    networks:
      - skynet

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS-root}
    networks:
      - skynet

  postgres:
    container_name: 'dockerized-postgres'
    image: postgres
    restart: ${RESTART_MONGO-no}
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER-root}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASS-root}
    volumes:
      - ${POSTGRES_DATA_DIR-./volumes/var/lib/postgresql/data}:/var/lib/postgresql/data
    networks:
      - skynet

  varnish:
    container_name: 'dockerized-varnish'
    build:
      context: ./services/varnish
      args:
        - VARNISH_PORT=${VARNISH_PORT-8080}
        - VARNISH_MALLOC=${VARNISH_MALLOC-128M}
    ports:
      - "${VARNISH_PORT-8080}:${VARNISH_PORT-8080}"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    volumes:
      - ./services/varnish/config/default.vcl:/etc/varnish/default.vcl
    networks:
      - skynet

  redis:
    container_name: 'dockerized-redis'
    restart: ${RESTART_REDIS-no}
    image: redis:alpine
    ports:
      - "${REDIS_PORT-6379}:6379"
    networks:
      - skynet

  memcached:
    container_name: 'dockerized-memcached'
    image: memcached:alpine
    restart: ${RESTART_MEMCACHED-no}
    ports:
      - "${MEMCACHED_PORT-11211}:11211"
    networks:
      - skynet

  ftp:
    container_name: 'dockerized-ftp'
    build:
      context: ./services/ftp
      args:
        - FTP_USER=${FTP_USER-john}
        - FTP_PASS=${FTP_PASS-doe}
    tty: true
    restart: ${RESTART_FTP-no}
    network_mode: host
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    volumes:
      - ${FTP_ROOT-./volumes/var/ftp}:/home/${FTP_USER-john}/ftp/files

  void:
    container_name: 'dockerized-void'
    build:
      context: ./services/void
      args:
        - VOID_USER=${VOID_USER-copernicus}
        - USE_BD_MIRRORS=${USE_BD_MIRRORS-false}
        - VOID_ADD_DEVEL=${VOID_ADD_DEVEL-false}
        - VOID_ADD_NODEJS=${VOID_ADD_NODEJS-true}
        - VOID_ADD_RUBY=${VOID_ADD_RUBY-false}
        - VOID_ADD_JDK=${VOID_ADD_JDK-false}
        - VOID_ADD_PYTHON=${VOID_ADD_PYTHON-false}
        - VOID_ADD_COMPOSER=${VOID_ADD_COMPOSER-true}
        - VOID_ADD_DRUSH=${VOID_ADD_DRUSH-false}
        - VOID_ADD_DRUPALCONSOLE=${VOID_ADD_DRUPALCONSOLE-false}
        - VOID_ADD_WPCLI=${VOID_ADD_WPCLI-false}
    tty: true
    stdin_open: true
    restart: ${RESTART_VOID-no}
    ports:
      - "${VOID_SSH_PORT-2222}:22"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - skynet
    environment:
      - DOCUMENT_ROOT=${DOCUMENT_ROOT-/var/www/html}
    volumes:
      - ${DOCUMENT_ROOT-./volumes/var/www/html}:/var/www/html
      - ${CACHE_DIR-./volumes/var/cachedir}:/var/cachedir
      - ${APACHE_LOG_DIR-./volumes/var/log/apache2}:/var/log/apache2
      - ${NGINX_LOG_DIR-./volumes/var/log/nginx}:/var/log/nginx
      - ./volumes/data/share:/data/share
      - ./volumes/root/.ssh:/root/.ssh
      - ./volumes/home/${VOID_USER-copernicus}/.ssh:/home/${VOID_USER-copernicus}/.ssh

  emby:
    container_name: 'dockerized-emby'
    image: emby/embyserver
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - ${EMBY_CONFIG-./volumes/emby/config}:/config
      - ${SHARED_DISK1-./volumes/mnt/disk1}:/mnt/disk1
      - ${SHARED_DISK2-./volumes/mnt/disk2}:/mnt/disk2

  alpine:
    container_name: 'dockerized-alpine'
    image: alpine:latest

  debian:
    container_name: 'dockerized-debian'
    image: debian:stretch-slim

  test:
    container_name: 'dockerized-test'
    build:
      context: ./services/test
    tty: true
    stdin_open: true
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - skynet
